# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_survey', '0002_questionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='call_sid',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('yes-no', 'Yes or no'), ('numeric', 'Numeric')], max_length=255),
        ),
    ]
